# generated by fastapi-codegen:
#   filename:  specification.yaml
#   timestamp: 2023-01-10T21:52:29+00:00

from __future__ import annotations

from fastapi import FastAPI
import uvicorn

from models import PredictSentimentsPostRequest, PredictSentimentsPostResponse

from inference import predict_sentiment

app = FastAPI(
    title='Sentiment Classification API',
    version='0.1.0',
    servers=[{'url': 'http://localhost:8000/'}],
)


@app.post('/predict_sentiments', response_model=PredictSentimentsPostResponse)
def post_predict_sentiments(
    body: PredictSentimentsPostRequest,
) -> PredictSentimentsPostResponse:
    """
    Predict sentiments probabilities
    """
    return predict_sentiment(body.text)

if __name__ == '__main__':
    uvicorn.run(app, host="0.0.0.0", port=9158)

