# generated by fastapi-codegen:
#   filename:  specification.yaml
#   timestamp: 2023-01-10T21:52:29+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PredictSentimentsPostRequest(BaseModel):
    text: Optional[str] = Field(None, description='Text to predict sentiments')


class Probabilities(BaseModel):
    neutral: Optional[float] = None
    positive: Optional[float] = None
    negative: Optional[float] = None


class PredictSentimentsPostResponse(BaseModel):
    pred_label: Optional[str] = Field(None, description='Predicted sentiment.')
    probabilities: Optional[Probabilities] = None
